spring:
  # active profile
  config:
    activate:
      on-profile: prod
  datasource:
    # use h2 embedded
    url: jdbc:log4jdbc:mysql://localhost:3306/hoxy_db?characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 1234
  jpa:
    hibernate:
      # ddl-auto: create # session factory 시작 시 drop and create
      ddl-auto: update # 변경된 스키마 update
    # show jpa query log
    properties:
      hibernate:
        show_sql: true
        format_sql: true