spring:
  # default profile
  profiles:
    active: dev
  #h2 database console
  h2:
    console:
      enabled: true
      path: /h2-console
  # use not found exception handler
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false